### ISSUE TITLE
v1.0.0 Windows failure

### ISSUE THREAD

**Issue by jblaine** [jtimberman/virtualbox-cookbook#1]
```
NoMethodError←[0m
-------------←[0m
undefined method `vbox_version' for Vbox::Helpers:Module←[0m

←[0m
Cookbook Trace:←[0m
---------------←[0m
  c:/var/cache/chef/cookbooks/virtualbox/attributes/default.rb:29:in `from_file'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/mixin/from_file.rb:30:in `i
nstance_eval'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/mixin/from_file.rb:30:in `f
rom_file'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/dsl/include_attribute.rb:39
:in `block in include_attribute'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/dsl/include_attribute.rb:31
:in `each'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/dsl/include_attribute.rb:31
:in `include_attribute'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compil
er.rb:169:in `load_attribute_file'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compil
er.rb:158:in `load_attributes_from_cookbook'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compil
er.rb:109:in `block in compile_attributes'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compil
er.rb:108:in `each'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compil
er.rb:108:in `compile_attributes'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context/cookbook_compil
er.rb:71:in `compile'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/run_context.rb:86:in `load'

  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:224:in `setup_run
_context'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:467:in `do_run'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/client.rb:200:in `run'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:190:in `run_
chef_client'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/client.rb:297:i
n `block in run_application'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/client.rb:290:i
n `loop'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application/client.rb:290:i
n `run_application'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/lib/chef/application.rb:73:in `run'
  c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.0/bin/chef-client:26:in `<top (require
d)>'
  c:/opscode/chef/bin/chef-client:23:in `load'
  c:/opscode/chef/bin/chef-client:23:in `<main>'←[0m

←[0m
Relevant File Content:←[0m
----------------------←[0m
c:/var/cache/chef/cookbooks/virtualbox/attributes/default.rb:

 22:  default['virtualbox']['version'] = ''
 23:
 24:  case node['platform_family']
 25:  when 'mac_os_x'
 26:    default['virtualbox']['url'] = 'http://download.virtualbox.org/virtualbox/4.2.8/VirtualBox-4
.2.8-83876-OSX.dmg'
 27:  when 'windows'
 28:    default['virtualbox']['url'] = 'http://download.virtualbox.org/virtualbox/4.2.8/VirtualBox-4
.2.8-83876-Win.exe'
 29>>   default['virtualbox']['version'] = Vbox::Helpers.vbox_version(node['virtualbox']['url'])
 30:  when 'debian', 'rhel'
 31:    default['virtualbox']['version'] = '4.2'
 32:  end
 33:  ←[0m
```

**Comment by jeremymv2** [comment]
I get this error as well..  any ideas from anybody?

**Comment by jtimberman** [comment]
This repository is my fork of [Chris Peplin's virtualbox cookbook](https://supermarket.chef.io/cookbooks/virtualbox) - there is no version 1.0.0 here. Looks like the repo for the cookbook on Supermarket is [a fork of this one](https://github.com/bradleyd/virtualbox-cookbook). So that's probably confusing, but I'm not really doing much with this cookbook anymore.
